### ISSUE TITLE
An illegal reflective access operation has occurred

### ISSUE THREAD

**Issue by artsenius** [gemini-testing/hermione-allure-reporter#22]
Hi guys,

I'm getting familiar with `hermione` and `hermione-allure-reporter`. Everything installed and configured according to the requirements.
Test are passed. The folder `allure-results` successfully created after a test run with the xml-files inside.
However, when I'm trying to generate report, I get this error:
```
$ allure generate allure-results/

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$2 (file:/C:/Users/Arthur/AppData/Roaming/npm/node_modules/allure-commandline/dist/bin/../app/allure-bundle.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,b
yte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$2
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[main] ERROR ru.yandex.qatools.allure.data.utils.ServiceLoaderUtils - ru.yandex.qatools.allure.data.plugins.Plugin: Provider ru.yandex.qatools.allure.data.plugins.MigrationPlugin could not be instantiated
[main] ERROR ru.yandex.qatools.allure.data.utils.ServiceLoaderUtils - ru.yandex.qatools.allure.data.plugins.Plugin: Provider ru.yandex.qatools.allure.data.plugins.EnvironmentPlugin could not be instantiated
Exception in thread "main" com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) Error injecting constructor, java.lang.NoClassDefFoundError: javax/xml/bind/ValidationEventLocator
  at ru.yandex.qatools.allure.data.converters.DefaultTestCaseConverter.<init>(DefaultTestCaseConverter.groovy:35)
  while locating ru.yandex.qatools.allure.data.converters.DefaultTestCaseConverter
  while locating ru.yandex.qatools.allure.data.converters.TestCaseConverter
    for field at ru.yandex.qatools.allure.data.AllureReportGenerator.converter(AllureReportGenerator.java:37)
  while locating ru.yandex.qatools.allure.data.AllureReportGenerator

1 error
        at com.google.inject.internal.Errors.throwProvisionExceptionIfErrorsExist(Errors.java:482)
        at com.google.inject.internal.MembersInjectorImpl.injectMembers(MembersInjectorImpl.java:67)
        at com.google.inject.internal.InjectorImpl.injectMembers(InjectorImpl.java:984)
        at ru.yandex.qatools.allure.data.AllureReportGenerator.<init>(AllureReportGenerator.java:48)
        at ru.yandex.qatools.allure.data.AllureReportGenerator.<init>(AllureReportGenerator.java:41)
        at ru.yandex.qatools.allure.data.AllureReportGenerator.<init>(AllureReportGenerator.java:37)
        at ru.yandex.qatools.allure.AllureMain.main(AllureMain.java:47)
Caused by: java.lang.NoClassDefFoundError: javax/xml/bind/ValidationEventLocator
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(Unknown Source)
        at java.base/java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(Unknown Source)
        at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(Unknown Source)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(Unknown Source)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
        at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
        at java.base/java.lang.Class.privateGetDeclaredMethods(Unknown Source)
        at java.base/java.lang.Class.privateGetPublicMethods(Unknown Source)
        at java.base/java.lang.Class.getMethods(Unknown Source)
        at org.codehaus.groovy.reflection.stdclasses.CachedSAMClass.getSAMMethod(CachedSAMClass.java:161)
        at org.codehaus.groovy.reflection.ClassInfo.isSAM(ClassInfo.java:356)
        at org.codehaus.groovy.reflection.ClassInfo.createCachedClass(ClassInfo.java:346)
        at org.codehaus.groovy.reflection.ClassInfo.access$700(ClassInfo.java:38)
        at org.codehaus.groovy.reflection.ClassInfo$LazyCachedClassRef.initValue(ClassInfo.java:494)
        at org.codehaus.groovy.reflection.ClassInfo$LazyCachedClassRef.initValue(ClassInfo.java:485)
        at org.codehaus.groovy.util.LazyReference.getLocked(LazyReference.java:46)
        at org.codehaus.groovy.util.LazyReference.get(LazyReference.java:33)
        at org.codehaus.groovy.reflection.ClassInfo.getCachedClass(ClassInfo.java:108)
        at org.codehaus.groovy.reflection.ReflectionCache.getCachedClass(ReflectionCache.java:107)
        at org.codehaus.groovy.reflection.CachedClass$8.initValue(CachedClass.java:206)
        at org.codehaus.groovy.reflection.CachedClass$8.initValue(CachedClass.java:197)
        at org.codehaus.groovy.util.LazyReference.getLocked(LazyReference.java:46)
        at org.codehaus.groovy.util.LazyReference.get(LazyReference.java:33)
        at org.codehaus.groovy.reflection.CachedClass.getInterfaces(CachedClass.java:249)
        at org.codehaus.groovy.reflection.CachedClass.<init>(CachedClass.java:235)
        at org.codehaus.groovy.reflection.ClassInfo.createCachedClass(ClassInfo.java:349)
        at org.codehaus.groovy.reflection.ClassInfo.access$700(ClassInfo.java:38)
        at org.codehaus.groovy.reflection.ClassInfo$LazyCachedClassRef.initValue(ClassInfo.java:494)
        at org.codehaus.groovy.reflection.ClassInfo$LazyCachedClassRef.initValue(ClassInfo.java:485)
        at org.codehaus.groovy.util.LazyReference.getLocked(LazyReference.java:46)
        at org.codehaus.groovy.util.LazyReference.get(LazyReference.java:33)
        at org.codehaus.groovy.reflection.ClassInfo.getCachedClass(ClassInfo.java:108)
        at org.codehaus.groovy.reflection.ReflectionCache.getCachedClass(ReflectionCache.java:107)
        at org.codehaus.groovy.reflection.ParameterTypes.getParametersTypes0(ParameterTypes.java:78)
        at org.codehaus.groovy.reflection.ParameterTypes.getParameterTypes(ParameterTypes.java:64)
        at org.codehaus.groovy.runtime.metaclass.MetaMethodIndex.isMatchingMethod(MetaMethodIndex.java:450)
        at org.codehaus.groovy.runtime.metaclass.MetaMethodIndex.addMethodToList(MetaMethodIndex.java:375)
        at groovy.lang.MetaClassImpl.addMetaMethodToIndex(MetaClassImpl.java:2950)
        at groovy.lang.MetaClassImpl.populateMethods(MetaClassImpl.java:393)
        at groovy.lang.MetaClassImpl.fillMethodIndex(MetaClassImpl.java:341)
        at groovy.lang.MetaClassImpl.initialize(MetaClassImpl.java:3261)
        at org.codehaus.groovy.reflection.ClassInfo.getMetaClassUnderLock(ClassInfo.java:251)
        at org.codehaus.groovy.reflection.ClassInfo.getMetaClass(ClassInfo.java:282)
        at ru.yandex.qatools.allure.data.converters.DefaultTestCaseConverter.$getStaticMetaClass(DefaultTestCaseConverter.groovy)
        at ru.yandex.qatools.allure.data.converters.DefaultTestCaseConverter.<init>(DefaultTestCaseConverter.groovy:35)
        at ru.yandex.qatools.allure.data.converters.DefaultTestCaseConverter$$FastClassByGuice$$c3bbad06.newInstance(<generated>)
        at com.google.inject.internal.cglib.reflect.$FastConstructor.newInstance(FastConstructor.java:40)
        at com.google.inject.internal.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:61)
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:105)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:85)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:267)
        at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:56)
        at com.google.inject.internal.SingleFieldInjector.inject(SingleFieldInjector.java:54)
        at com.google.inject.internal.MembersInjectorImpl.injectMembers(MembersInjectorImpl.java:132)
        at com.google.inject.internal.MembersInjectorImpl$1.call(MembersInjectorImpl.java:93)
        at com.google.inject.internal.MembersInjectorImpl$1.call(MembersInjectorImpl.java:80)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
        at com.google.inject.internal.MembersInjectorImpl.injectAndNotify(MembersInjectorImpl.java:80)
        at com.google.inject.internal.MembersInjectorImpl.injectMembers(MembersInjectorImpl.java:62)
        ... 5 more
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.ValidationEventLocator
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
        ... 68 more
Command aborted due to exception {}.
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
        at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404)
        at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:166)
        at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:153)
        at ru.yandex.qatools.allure.command.ReportGenerate.runUnsafe(ReportGenerate.java:48)
        at ru.yandex.qatools.allure.command.AbstractCommand.run(AbstractCommand.java:52)
        at ru.yandex.qatools.allure.CommandLine.main(CommandLine.java:46)
```
Project repository located here:
https://github.com/artsenius/automation-hermione

Thank you in advance.

**Comment by ABirar** [comment]
@artsenius : Were you able to resolve this issue ? I am facing same error.

**Comment by j0tunn** [comment]
hermione-allure-reporter is not supported since 2016. Please, use [html-reporter](https://github.com/gemini-testing/html-reporter)
